services:

    security.access.donreach_article_metrics_voter:
        class:      Seriel\DonReachBundle\Securite\Voters\DonReachArticleMetricsVoter
        public:     false
        arguments: ["@service_container"]
        tags:
           - { name: security.voter }

    seriel_donreach.manager:
        class: Seriel\DonReachBundle\Managers\DonReachManager
        arguments: ["@service_container", "@logger", "%donreach%"]
        
    seriel_donreach.article_metrics_manager:
        class: Seriel\DonReachBundle\Managers\DonReachArticleMetricsManager
        arguments: ["@doctrine", "@logger", "@service_container"]
        